Script started on 2017年03月15日 (週三) 01時30分24秒
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~ $[00m whoami; pwd
pd2vm
/home/pd2vm
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~ $[00m  git config -l
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~ $[00m  git clone https://github.com/E24054180/lab1
Cloning into 'lab1'...
warning: You appear to have cloned an empty repository.
Checking connectivity... done.
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~ $[00m 
Script done on 2017年03月15日 (週三) 01時31分15秒
